/**
 * Generates public/sitemap.xml.
 *
 * Was hand-maintained and listed five English URLs. With four languages that
 * is twenty, each needing to declare the other three, so it is generated now —
 * a hand-written matrix of eighty xhtml:link elements would drift the first
 * time a page was added.
 *
 * Every URL carries the FULL alternate set including itself, which is what the
 * spec requires: a crawler that reaches any one of the four must be able to
 * discover the other three from that entry alone. This is the other half of
 * the contract with middleware.js — the redirect only stays safe for indexing
 * because the alternates are declared here and in each page's <head>.
 */
import { writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ALL_LOCALES, DEFAULT_LOCALE, LOCALE_META, ORIGIN, ROUTES } from './i18n-transform.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const href = (locale, route) =>
  `${ORIGIN}${locale === DEFAULT_LOCALE ? '' : '/' + locale}${route === '/' ? '/' : route}`;

function main() {
  // Only advertise a language that actually built.
  const locales = ALL_LOCALES.filter(
    (l) => l === DEFAULT_LOCALE || existsSync(resolve(ROOT, `src/data/i18n/${l}.json`)),
  );
  const lastmod = new Date().toISOString().slice(0, 10);
  const routes = Object.values(ROUTES);

  const urls = locales.flatMap((locale) =>
    routes.map((route) => {
      const alts = [
        ...locales.map(
          (l) => `    <xhtml:link rel="alternate" hreflang="${LOCALE_META[l].lang}" href="${href(l, route)}" />`,
        ),
        `    <xhtml:link rel="alternate" hreflang="x-default" href="${href(DEFAULT_LOCALE, route)}" />`,
      ].join('\n');
      return `  <url>\n    <loc>${href(locale, route)}</loc>\n    <lastmod>${lastmod}</lastmod>\n${alts}\n  </url>`;
    }),
  );

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/build-sitemap.mjs. Do not edit by hand.
     The five indexable pages in every built language. 404.html is noindex and
     intentionally absent. URLs are extensionless to match Vercel cleanUrls and
     each page's canonical; .html paths 308-redirect and must never appear here.
     <changefreq> and <priority> are omitted on purpose: Google ignores both,
     and a stale "yearly" on an actively edited page is worse than no signal. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.join('\n')}
</urlset>
`;

  writeFileSync(resolve(ROOT, 'public/sitemap.xml'), xml);
  console.log(`build-sitemap: ${urls.length} URLs across ${locales.length} language(s) -> public/sitemap.xml`);
}

if (process.argv[1] && resolve(fileURLToPath(import.meta.url)) === resolve(process.argv[1])) main();
